googleapis/nodejs-logging-bunyan

package.json
samples/package.json

Release notes in the releases draft area.

Bump version to 0.7.0

---

package-lock.json
src/index.ts
src/types/core.d.ts
system-test/logging-bunyan.ts

chore: fix system tests

---

.circleci/config.yml

- correct sequence of link + install for samples
- run `npm install` before `npm publish` for TS code
Fixes #47.

chore: fixes to CircleCI config

---

package-lock.json
package.json
samples/package-lock.json
samples/package.json

Release notes are in the [GitHub UI](https://github.com/googleapis/nodejs-logging-bunyan/releases/tag/untagged-8ee77f223fa6342a7ffd).

chore: release v0.8.1

---

src/index.ts
test/index.ts

Fixes: https://github.com/googleapis/nodejs-logging-bunyan/issues/59
Fixes #59

fix: properly attach severity to entries

---

package-lock.json
package.json
samples/package-lock.json

Release notes in https://github.com/googleapis/nodejs-logging-bunyan/releases/tag/untagged-c5eb37e659724dcb4f95 (only project members will be able to follow link).

chore: release v0.8.2

---

package-lock.json
package.json

test: use source-map-support

---

samples/quickstart.js
samples/setup_explicit.js

Also made a style improvement in the meanwhile.

fix(samples): fix non-working explit setup sample

---

.eslintrc.yml
samples/express.js
samples/package-lock.json
samples/package.json
samples/system-test/express.test.js

Follow-on to #63, this PR adds a sample that should solidify the DX.

feat(samples): add express middleware sample

---

README.md
package-lock.json

doc: add express middleware to README

---

package.json

This is needed for https://github.com/googleapis/nodejs-logging-bunyan/issues/123.

chore(deps): upgrade to @g-c/logging@3

---

CHANGELOG.md
package.json

Release nodejs-logging-bunyan v0.9.1

---

package.json
samples/package.json
samples/system-test/express.test.js
src/index.ts
system-test/logging-bunyan.ts
system-test/test-middleware-express.ts
test/index.ts

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

Update @google-cloud/logging to 4.x

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging-bunyan v0.9.2

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging-bunyan v0.9.4

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging-bunyan v0.9.5

---

src/middleware/express.ts
test/middleware/test-express.ts

feat(middleware): generate parent request logs

---

README.md

This blocked reference docs publishing :(

nit: use https for links

---

package.json
system-test/errors-transport.ts

The system tests were dependent on @g-c/common, but didn't declare it.
This meant that we unwittingly picked up a semver major change causing
build to be failing at master.

fix: directly depend on @g-c/common

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging-bunyan v0.10.0

---

system-test/errors-transport.ts
system-test/logging-bunyan.ts

Debugging the system tests more

More deflaking of the error reporting system test

---

CHANGELOG.md
package.json
samples/package.json

Release @google-cloud/logging-bunyan v0.10.1

---

.gitignore
.readme-partials.yml
.repo-metadata.json
README.md
samples/README.md
samples/setup_explicit.js
synth.metadata

* adds new `.repo-metadata.json`, used for `googleapis.dev` doc generation.
* re-generates README.md using template.

feat: add .repo-metadata.json, generate docs
