src/index.ts
src/types.d.ts

BREAKING CHANGE. If the record contains a labels property, promote it to
the entry metadata. This allows label based filtering in the Logging UI.
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry
Counterpart to  https://github.com/googleapis/nodejs-logging-winston/pull/23

feat: promote record labels to metadata

---

.circleci/config.yml

One more place to apply the same fix as in #48, this time to make samples tests work.

chore: run npm link before npm install

---

README.md

Since we are using a protobuf based transport, users need to format
according to the protobuf docs rather than the JSON/REST docs.
Ref: https://github.com/googleapis/nodejs-logging-winston/issues/93

doc: fix link to HttpRequest message

---

.circleci/config.yml
package.json

BREAKNG CHANGE: This library is no longer supported for node.js 4.x or 9.x.

fix: drop support for node 4.x and 9.x

---

system-test/logging-bunyan.ts

The system tests write to the `bunyan_log_system_tests` log to
avoid conflicting with the sample tests.
Fixes: #49

fix: the system tests use a custom log

---

README.md

Fixes #66
This fixes the misleading README example highlighted in issue above, using https://github.com/googleapis/nodejs-logging-bunyan/issues/66#issuecomment-397791037 as a reference, and that `LOGGING_TRACE_KEY` exists on module exports, not the `LoggingBunyan` class.

doc: fix usage of logger.info in README.md

---

package-lock.json
package.json
src/index.ts
src/middleware/express.ts
src/types/core.d.ts
system-test/test-middleware-express.ts

Opening this early to get feedback. This is still WIP. Please take a look at the example in `system-test/` directory and provide feedback on whether the default UX for logging looks reasonable. For comparison, this is the boilerplate we require today: https://github.com/googleapis/nodejs-logging-bunyan#using-the-client-library. @JustinBeckwith @fhinkel @googleapis/node-team 
This change introduces a mechanism to export middleware – only express
added at this point – others are possible in the future.
The middleware makes it simple to start logging from express apps
without having to deal with boilerplate to initialize bunyan and the
stackdriver stream separately.
Furthermore, the middleware exposes a `log` API on the `request` object
that can do context-correlation. All log entries …

feat: request-correlating middleware

---

.eslintrc.yml
samples/package.json

`eslint` was reporting the following error:
```
error  Async functions are not supported until Node.js 7.6.0. The configured version range is '>=6.0.0'  node/no-unsupported-features/es-syntax
```
This happened because `eslint` has a new `node/no-unsupported-features/es-syntax` that by default reports an error.
The error occurs because the samples use async/await, async/await is not available until Node >= 7.6.0, and the samples `package.json` specifies only Node >= 6.0 is required.
To fix the linting errors, the `node/no-unsupported-features/es-syntax` was configured to only issue a warning.
This was done, instead of updating the `package.json` to specify that Node >= 7.6.0 is required,   since the library `@google-cloud/logging-bunyan` library only requires Node >= 6.0.0.  It is only if …

fix: fix linting errors in the samples

---

samples/README.md

Replaces "Winston" with "Bunyan" in samples/README.md

doc: fix typo in samples/README

---

package.json

There is an issue with delay@3.1.0 with the included types.  This
is being tracked at delay
[issue #32](https://github.com/sindresorhus/delay/issues/32) and
is preventing @google-cloud/logging-bunyan from compiling.
Until delay issue #32 is resolved, delay will be pinned to version
3.0.x.

chore: pin to delay@3.0.x

---

package.json
samples/package.json
system-test/test-middleware-express.ts

The package started shipping types as part of the official
package.  These are breaking changes w.r.t previous
`@types/delay` types.  We need to import the module differently
now for things to work correctly.

chore(package): upgrade to delay@3.1.0

---

src/index.ts
src/middleware/express.ts

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)

fix: doc string is malformed for jsdoc

---

src/middleware/express.ts

It turns out bunyan provides built-in support for Child loggers to
insert scope specific keys into the log metadata. This means that
we don't have to hand-roll an approximation to the bunyan API.
There should be no functional changes for JS users. TS users will see
the types change. Given that this support is clearly marked as
experimental in the docs, we are not going to deem these as semver
major changes.

fix(middleware): use bunyan log.child

---

package.json
samples/express.js
samples/system-test/express.test.js
src/middleware/express.ts
system-test/test-middleware-express.ts
test/middleware/test-express.ts

Start using refactored code from @g-c/logging.

refactor(middleware): use common code from logging

---

src/middleware/express.ts

Upstream fix has been released and we longer need to deep link to
envDetect in google-auth-library.

fix: remove deep dependency into auth-library

---

package.json
system-test/logging-bunyan.ts
system-test/test-install.ts
system-test/test-middleware-express.ts

Ref: https://github.com/googleapis/nodejs-logging-winston/pull/265
1. Synchronize the system test with logging-winston. Use the same
structure and reliable mechanism for polling.
2. Apply the timeout uniformly across the test.
3. Use unique serviceContext for the error reporting tests to ensure
concurrent executions of the tests do no race.

fix: de-flake system tests

---

README.md
src/index.ts
test/index.ts

We promote a bunyan record.labels property to the LogEntry.labels
property. This enables label based filtering to work auto-magically.
However, this can be problematic when the labels are not type correct
as per the logging proto requirements - specifically, the labels values
have to be strings.
Restrict the automatic promotion to happen only in the cases when
know that the labels are well-formatted.
Fixes: https://github.com/googleapis/nodejs-logging-bunyan/issues/265

fix: do not promote record.labels if improper

---

samples/express.js
samples/system-test/express.test.js

This allows multiple runs of the samples tests to occur on the
same machine at the same time to test for conflicts between
concurrently running tests.

chore: allow custom port in samples tests

---

system-test/errors-transport.ts
system-test/logging-bunyan.ts

The system tests for error reporting were still not safe to run
concurrently. The issue is that at the end we were deleting all events
(there is no API to delete events selectively, AFAICT). This meant that
concurrent executions of the system tests against the same project could
clobber anothers logged errors.
This is consistent with the observed timeouts looking for events to
show up.
Fixes #267

test: fix error reporting system test race

---

system-test/errors-transport.ts

Previously we were comparing the list of services using the
representative sample. This means that if more than one service have the
same error, we may not necessarily get the sample that we want to
observe. Instead look for all the affected services for all groups to
find the matching group.
Ref: https://github.com/googleapis/nodejs-logging-winston/pull/279

test: make error reporting system test more robust

---

package.json

We use this at runtime.
Fixes: https://github.com/googleapis/nodejs-logging-bunyan/issues/277

fix: add missing dep on google-auth-library

---

src/index.ts

Our overrides for Writable.prototype._write[v] didn't match the
signature of the parent class. encoding and callback are not optional.
Users of the module don't call these directly, so these should be `semver-patch`.

fix: proper signature for _write[v]

---

src/index.ts
system-test/errors-transport.ts
test/index.ts

When running on GCP environments, automatically detect service context
so that error reporting can correctly pick up errors.
Fixes: https://github.com/googleapis/nodejs-logging-bunyan/issues/135

feat: auto-detect service context

---

package.json
src/index.ts
src/types/core.d.ts
test/index.ts

see: https://github.com/googleapis/nodejs-logging-winston/issues/190

feat!: log messages > 250,000 bytes are now truncated

---

system-test/logging-bunyan.ts

Adds retry logic for a couple tests that are hitting a 90 second limit occasionally.

test: retry tests that intermittently timeout

---

samples/system-test/express.test.js

waiting for a specific message to be in stackdriver is fragile, instead let's simply assert that our sample created a functional express server with logging.

test: don't wait for specific message
